# Generated by Django 4.1.7 on 2025-09-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='batch',
            field=models.CharField(blank=True, help_text='e.g., 2010-2014', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science & Engineering'), ('EC', 'Electronics & Communication Engineering'), ('EE', 'Electrical & Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('IT', 'Information Technology'), ('MCA', 'MCA'), ('MBA', 'MBA')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='year_of_passing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
