# Generated by Django 4.1.7 on 2025-10-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_batch_profile_course_profile_year_of_passing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='batch',
        ),
        migrations.AddField(
            model_name='profile',
            name='batch_year_range',
            field=models.CharField(blank=True, help_text='e.g., 2021-2024', max_length=50, null=True),
        ),
    ]
