# Generated by Django 4.1.7 on 2025-10-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_profile_batch_profile_batch_year_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='year_of_passing',
        ),
    ]
