# Generated by Django 4.1.7 on 2025-10-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profile_year_of_passing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='course',
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science & Engineering'), ('EC', 'Electronics & Communication Engineering'), ('EE', 'Electrical & Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('IT', 'Information Technology'), ('MCA', 'MCA'), ('MBA', 'MBA')], max_length=50, null=True),
        ),
    ]
