# Generated by Django 4.1.7 on 2025-10-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_profile_course_alter_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('EC', 'Electronics & Communication Engineering'), ('EE', 'Electrical & Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('INMCA', 'INTEGRATED MCA'), ('MCA', 'MCA'), ('MBA', 'MBA')], max_length=50, null=True),
        ),
    ]
