# Generated by Django 4.1.7 on 2025-10-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course_program',
            field=models.CharField(blank=True, choices=[('BT', 'B.Tech'), ('INMCA', 'MCA (Integrated)'), ('MBA', 'MBA'), ('MCA', 'MCA (Regular)')], max_length=50, null=True),
        ),
    ]
